#! /bin/sh

export MONGO_HOST=localhost
export MONGO_PORT=27017
export MONGO_DBNAME=esn
export REDIS_HOST=localhost
export REDIS_PORT=6379
export WEB_HOST=openpaas.local
export WEB_PORT=80
export DAV_SERVER_HOST=dav.openpaas.local
export DAV_SERVER_PORT=80
export ELASTICSEARCH_HOST=localhost
export ELASTICSEARCH_PORT=9200
export JMAP_SERVER_HOST=james.openpaas.local
export JMAP_SERVER_PORT=80
export AMQP_HOST=localhost
export AMQP_PORT=5672
export JAMES_WEBADMIN_HOST=james.openpaas.local
export JAMES_WEBADMIN_PORT=8000
export MAIL_BROWSER=false
export SMTP_HOST=james.openpaas.local
export SMTP_PORT=25
